export const fakePillarInfo = () => ({
  title: 'Dexes Projects',
  count: 331,
  description:
    'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer ut odio eu ante laoreet tincidunt id eget dui. Suspendisse interdum, tortor at tempus pulvinar, elit libero consequat nulla, id mollis elit mauris ac est.',
  activePillar: {
    slug: 'categories',
    items: [
      'Dexes Projects in Crypto',
      'Bizdev Projects',
      'Customer Support Projects',
      'Cybersecurity Projects',
      'Data Science Jobs',
      'Category 1',
      'Data Entry Jobs',
      'Design Jobs',
      'DevOps Jobs',
      'Engineering Jobs',
      'Finance Jobs',
      'HR Jobs',
      'Legal Jobs',
      'Management Jobs',
      'Marketing Jobs',
    ],
  },
  altPillar: {
    slug: 'skills',
    items: [
      'Python',
      'JavaScript',
      'React',
      'Node.js',
      'Angular',
      'Vue.js',
      'Django',
      'Flask',
      'Express',
      'MongoDB',
      'PostgreSQL',
      'Golang',
      'Java',
      'C++',
      'C#',
      'PHP',
      'Ruby',
      'Swift',
      'Kotlin',
      'Rust',
      'Scala',
      'TypeScript',
      'HTML',
      'CSS',
      'SASS',
      'LESS',
    ],
  },
});
