name: Feature Branch

on:
  push:
    branches-ignore: [main] # run only on feature-branch
  workflow_dispatch: # option to manual trigger workflow

concurrency: # cancel duplicate
  group: feature-branch
  cancel-in-progress: true

jobs:
  # feature-branch lint/build/test
  lint-build-test:
    name: Run Lint/Build/Test
    runs-on: ubuntu-latest
    env:
      NEXT_PUBLIC_MW_URL: https://middleware.jobstash.xyz
      NEXT_PUBLIC_FRONTEND_URL: https://projects.fyi
      NEXT_PUBLIC_PAGE_SIZE: 20
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
        name: Install pnpm
        id: pnpm-install
        with:
          version: 8
          run_install: false
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'pnpm'
      - name: Install deps
        run: pnpm install
      - name: Run Lint
        run: pnpm lint
      # - name: Run Build
      #   run: pnpm build
      - name: Run Test
        run: pnpm test

  # TODO: deploy staging
  # TODO: e2e test